### ISSUE TITLE
Add dark mode to app

### ISSUE THREAD

**Issue by virejdasani** [virejdasani/MeetingAssistant#1]

**Comment by KashyapPavra** [comment]
Hey @virejdasani ! If this feature is still to be added, I would love to help you out

**Comment by virejdasani** [comment]
Hi @KashyapPavra it is yet to be added! 👍

**Comment by virejdasani** [comment]
@KashyapPavra any help would be greatly appreciated!

**Comment by KashyapPavra** [comment]
@virejdasani Great, can you assign me this issue? I'll have a look at it this weekend.

**Comment by virejdasani** [comment]
@KashyapPavra, If you can, add a dark mode toggle on the top right in the app, thanks in advance!

**Comment by KashyapPavra** [comment]
@virejdasani Sure I'll try adding that
